#ifndef QTLOCALAUTHENTICATORGLOBAL_P_H
#define QTLOCALAUTHENTICATORGLOBAL_P_H

#include <QtCore/qglobal.h>

QT_BEGIN_NAMESPACE

#ifndef QT_STATIC
#  if defined(QT_BUILD_LOCALAUTHENTICATOR_LIB)
#    define Q_LOCALAUTHENTICATOR_EXPORT Q_DECL_EXPORT
#  else
#    define Q_LOCALAUTHENTICATOR_EXPORT Q_DECL_IMPORT
#  endif
#else
#  define Q_QUICKTEMPLATES2_PRIVATE_EXPORT
#endif

QT_END_NAMESPACE

#endif // QTLOCALAUTHENTICATORGLOBAL_P_H
